### ISSUE TITLE
bool(false)

### ISSUE THREAD

**Issue by iojensen** [BlakeGardner/php-mac-address#2]
https://folkeposten.dk/test/

Code
// require the class
require_once $_SERVER['DOCUMENT_ROOT'].'/src/BlakeGardner/MacAddress.php';

// import the class
use BlakeGardner\MacAddress;

var_dump(MacAddress::getCurrentMacAddress('eth0'));
/Code

returns bool(false)

**Comment by juliangorge** [comment]
could you solved this?

**Comment by BlakeGardner** [comment]
@juliangorge what issue are you seeing?
